[package]
name = "scan_network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mac_address2 = "2.0.2"
networkmanager = { package = "passcod-networkmanager", version = "0.6.1" }
wifi-rs = "0.2.4"